apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myfunctionapp

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: myfunctionapp
  app.kubernetes.io/managed-by: kustomize

images:
  - name: myfunctionappnodejs-web
    newTag: latest

configMapGenerator:
  - name: web-config
    literals:
      - PORT="8080"
      - NODE_ENV="production"
